name: compress

on:
  push:
    tags:
      - 'GE-Proton*' # triggers the workflow for any tag pushed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:

  compress:

    runs-on: ubuntu-latest

    
    steps:
      - name: Download proton-ge-custom latest release
        uses: robinraju/release-downloader@v1
        with:
          repository: GloriousEggroll/proton-ge-custom
          latest: true
          fileName: 'GE-Proton*.tar.gz'
          
      - uses: robinraju/release-downloader@v1
        with:
          repository: GloriousEggroll/proton-ge-custom
          latest: true
          fileName: 'GE-Proton*.sha512sum'

      - name: preparation
        run: |
          grep "GE-Proton.*\.tar\.gz$" SHA512SUMS | sha512sum -c
          VER=$(basename GE-Proton*.tar.gz .tar.gz)
          echo "VER=${VER}" >> "$GITHUB_ENV"
          mv GE-Proton*.tar.gz proton.tar.gz
          mv GE-Proton*.sha512sum SHA512SUMS
          gzip -d proton.tar.gz

      - name: compress
        run: |
          xz -9e -T0 -v proton.tar
          mv proton.tar.xz "${VER}.tar.xz"
          sha512sum "${VER}.tar.xz" >> SHA512SUMS
          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VER }}.tar.xz
          path: ${{ github.workspace }}/${{ env.VER }}.tar.xz

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.workspace }}/${{ env.VER }}.tar.xz
            ${{ github.workspace }}/SHA512SUMS
          generate_release_notes: false
