name: compress

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    tags:
      - '*' # triggers the workflow for any tag pushed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:

  compress:

    runs-on: ubuntu-latest

    
    steps:
      - name: Download latest GE-Proton release
        uses: robinraju/release-downloader@v1
        with:
          repository: GloriousEggroll/proton-ge-custom
          latest: true
          fileName: 'GE-Proton*.tar.gz'

      - name: preparation
        run: |
          VER=$(basename GE-Proton*.tar.gz .tar.gz)
          echo "VER=${VER}" >> "$GITHUB_ENV"
          find . -maxdepth 1 -type f -name "GE-Proton*" -print0 | xargs -0 -I {} mv {} proton.tar.gz
          gzip -d proton.tar.gz

      - name: compress
        run: |
          xz -9e -T0 -v proton.tar

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VER }}.tar.xz
          path: ${{ github.workspace }}/proton.tar.xz

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.workspace }}/proton.tar.xz
          name:  ${{ env.VER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
