# This is a basic workflow to help you get started with Actions

name: compress

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compress:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Download latest release asset
        uses: robinraju/release-downloader@v1
        with:
          repository: GloriousEggroll/proton-ge-custom 
          latest: true
          fileName: 'GE-Proton*.tar.gz'

      - name: compress
        run: |
          find . -maxdepth 1 -type f -name "proton-ge-custom-GE-Proton*" -print0 | xargs -0 -I {} mv {} proton.tar.gz
          mkdir proton
          tar -xvzf proton.tar.gz -C proton
          7z a -t7z -mx=9 -m0=LZMA2 -mf=BCJ2 -md=32m -ms -mqs proton.7z proton/

      - uses: actions/upload-artifact@v4
        with:
          name: proton.7z
          path: ${{ github.workspace }}/proton.7z
