# This is a basic workflow to help you get started with Actions

name: compress

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compress:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download latest GE-Proton release
        uses: robinraju/release-downloader@v1
        with:
          repository: GloriousEggroll/proton-ge-custom
          latest: true
          fileName: 'GE-Proton*.tar.gz'

      - name: preparation
        run: |
          VER = $(basename GE-Proton*.tar.gz .tar.gz)
          echo "VER=${VER}" >> "$GITHUB_ENV"
          find . -maxdepth 1 -type f -name "GE-Proton*" -print0 | xargs -0 -I {} mv {} proton.tar.gz
          gzip -d proton.tar.gz

      - name: compress
        run: |
          xz -9 -e --lzma2=dict=1536MiB,lc=4,lp=0,pb=0,mode=normal,nice=273,mf=bt4,depth=512 -T0 proton.tar

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.VER }}.tar.xz
          path: ${{ github.workspace }}/proton.tar.xz

      - name: release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ env.VER }}.tar.xz
          name:  ${{ env.VER }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
